start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 
start crawler.bat "crawlPageforProxys('http://www.proxyfire.net/forum/');" 