start crawler.bat "testNewProxys();" 
start crawler.bat "testNewProxys();"
start crawler.bat "testNewProxys();"
start crawler.bat "testNewProxys();"
start crawler.bat "testNewProxys();" 
start crawler.bat "testNewProxys();"
start crawler.bat "testNewProxys();"
start crawler.bat "testNewProxys();"